import { formatUKTime } from "./dateTime.js";

/* Approved AC names */
export const AC_CONTACTS = [
  "Namir","Joel","Dionee","Simoné","Ryan","Conah","Thami","Melissa","Waldo",
  "Melvin","Tiffany","Albert","Alicia K","Alicia O","Ethan","Martin","Leonah",
  "Matthew","Siyabonga","Enock","Treasure","Melokuhle","Eugene","Bianca",
  "Jonathan","Bonolo","Willem","Shamiso","Miné","Songeziwe","Michelle",
  "Kwakhanya","Jennifer","Munyaradzi","Leroy","Cameron","Jenny","Yolandie",
  "Vanessa","Yael","Cynthia"
];

export const AC_EMAIL_MAP = {
  "Namir": "namir@actuaryconsulting.co.za",
  "Joel": "joel@actuaryconsulting.co.za",
  "Dionee": "dionee@actuaryconsulting.co.za",
  "Simoné": "simone@actuaryconsulting.co.za",
  "Ryan": "ryan@actuaryconsulting.co.za",
  "Conah": "conah@actuaryconsulting.co.za",
  "Thami": "thami@actuaryconsulting.co.za",
  "Melissa": "melissa@actuaryconsulting.co.za",
  "Waldo": "waldo@actuaryconsulting.co.za",
  "Melvin": "melvin@actuaryconsulting.co.za",
  "Tiffany": "tiffany@actuaryconsulting.co.za",
  "Albert": "albert@actuaryconsulting.co.za",
  "Alicia K": "aliciak@actuaryconsulting.co.za",
  "Alicia O": "aliciao@actuaryconsulting.co.za",
  "Ethan": "ethan@actuaryconsulting.co.za",
  "Martin": "martin@actuaryconsulting.co.za",
  "Leonah": "leonah@actuaryconsulting.co.za",
  "Matthew": "matthew@actuaryconsulting.co.za",
  "Siyabonga": "siya@actuaryspace.co.za",
  "Enock": "enock@actuaryconsulting.co.za",
  "Treasure": "treasure@actuaryconsulting.co.za",
  "Melokuhle": "melokuhle@actuaryconsulting.co.za",
  "Eugene": "eugene@actuaryconsulting.co.za",
  "Bianca": "bianca@actuaryconsulting.co.za",
  "Jonathan": "jonathan@actuaryconsulting.co.za",
  "Bonolo": "bonolo@actuaryconsulting.co.za",
  "Willem": "willem@actuaryconsulting.co.za",
  "Shamiso": "shamiso@actuaryconsulting.co.za",
  "Miné": "mine@actuaryconsulting.co.za",
  "Songeziwe": "songeziwe@actuaryconsulting.co.za",
  "Michelle": "michelle@actuaryconsulting.co.za",
  "Kwakhanya": "kwakhanya@actuaryconsulting.co.za",
  "Jennifer": "jennifer@actuaryconsulting.co.za",
  "Munyaradzi": "munyaradzi@actuaryconsulting.co.za",
  "Leroy": "leroy@actuaryconsulting.co.za",
  "Cameron": "cameron@actuaryconsulting.co.za",
  "Jenny": "jenny@actuaryconsulting.co.za",
  "Yolandie": "yolandie@actuaryspace.co.za",
  "Vanessa": "vanessa@actuaryconsulting.co.za",
  "Yael": "yael@actuaryconsulting.co.za",
  "Cynthia": "cynthia@actuaryconsulting.co.za"
};

/* ---------- Email draft templates (Yolandie picks one, then edits) ---------- */
export const DRAFT_TEMPLATES = [
  {
    id: "new_blank",
    label: "New Draft",
    body: "",
  },
  {
    id: "new_instr_ack",
    label: "New instructions – acknowledge & confirm trial / lodgement",
    body: [
      "Dear [Attorney Name],",
      "",
      "Thank you for your email and the new instructions in the above matter.",
      "",
      "We acknowledge receipt of the instruction letter and supporting documentation. ",
      "Kindly confirm the following so that we can proceed efficiently:",
      "1. Has this matter been lodged with the Road Accident Fund?",
      "2. Is there a trial date or any court deadline for this matter?",
      "",
      "Once we receive your confirmation (and any outstanding documents), we will proceed with our calculations and revert with an estimated turnaround time.",
      "",
      "Kind regards,",
      "Namir Waisberg",
      "Actuary Consulting",
    ].join("\n"),
  },
  {
    id: "awaiting_medicals",
    label: "Acknowledgement – awaiting medico-legal reports",
    body: [
      "Dear [Attorney Name],",
      "",
      "Thank you for your email and the documentation provided in respect of the above matter.",
      "",
      "We confirm safe receipt of the available documents. We note that certain medico-legal reports are still outstanding, and will commence our calculations once these have been received.",
      "",
      "Please feel free to let us know if there are any particular time constraints or court dates that we should be aware of.",
      "",
      "Kind regards,",
      "Namir Waisberg",
      "Actuary Consulting",
    ].join("\n"),
  },
  {
    id: "missing_income_docs",
    label: "Request – missing income / bank documents",
    body: [
      "Dear [Attorney Name],",
      "",
      "Thank you for your instructions in the above matter.",
      "",
      "We have reviewed the documents received and note that certain income-related records (e.g. payslips, bank statements and/or tax returns) are still outstanding.",
      "",
      "Kindly provide the missing income documents at your earliest convenience so that we can finalise the loss of earnings calculations.",
      "",
      "If there is any difficulty in obtaining these records, please let us know and we will advise on possible alternatives.",
      "",
      "Kind regards,",
      "Namir Waisberg",
      "Actuary Consulting",
    ].join("\n"),
  },
  {
    id: "progress_update",
    label: "Progress update – reassurance on timeline",
    body: [
      "Dear [Attorney Name],",
      "",
      "We refer to the above matter and confirm that we are in the process of finalising our actuarial calculations.",
      "",
      "All available documents have been captured and we are now working through the detailed projections. ",
      "Barring any unforeseen issues or further information requests, we anticipate reverting with a draft report by [date].",
      "",
      "Should any new information become available in the interim, please forward it to us so we can incorporate it before finalising.",
      "",
      "Kind regards,",
      "Namir Waisberg",
      "Actuary Consulting",
    ].join("\n"),
  },
  {
    id: "send_draft_report",
    label: "Cover email when sending draft report",
    body: [
      "Dear [Attorney Name],",
      "",
      "We attach herewith our draft actuarial report in respect of the above matter for your review.",
      "",
      "Kindly consider the contents and let us know if there are any factual corrections, additional information or points of clarification before we finalise the report.",
      "",
      "Once you are satisfied that the draft accords with your instructions and the available documentation, we will prepare and issue the signed final report.",
      "",
      "Kind regards,",
      "Namir Waisberg",
      "Actuary Consulting",
    ].join("\n"),
  },
];
